// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thpboeenwdggxewsztfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRocGJvZWVud2RnZ3hld3N6dGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzUyODcsImV4cCI6MjA1ODcxMTI4N30.ZOCOSS27wgNfH78zjvFuxvSK9VqQuldXiPh5adojVVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);